### ISSUE TITLE
256qam似乎无效?

### ISSUE THREAD

**Issue by MeIsReallyBa** [ferhung-mtk/padavan_mt7615_ap_v5.0.2.0#1]
手机电脑的2.4g链接速率均是未开256qam的结果。。。。op上正常 驱动本身应该没问题。

**Comment by MeIsReallyBa** [comment]
另外修改无线设置路由器重启才能生效。之前好像看到过，k2p这种dbdc的，修改了无线设置需要2.4g 5g均重启才有效?

**Comment by MeIsReallyBa** [comment]
eeflash.c里面应该就是Factory吧？padavan是Factory，op才是factory吧

**Comment by MeIsReallyBa** [comment]
额改成Factory后，eeprom读取正常了，256qam也好了。mt_mtd那个玩意也可以删了，op才需要，padavan有相关函数

**Comment by ferhung-mtk** [comment]
嗯，已更改!

**Comment by ferhung-mtk** [comment]
另外修改无线设置路由器重启才能生效的问题，@hanwckf已有解决方法，但是我更希望是从驱动本身解决，所以还没添加hanwckf的path.
